name: testing gh api

on:
  push:
  
permissions: write-all

jobs:
  comment-with-api:
    runs-on: ubuntu-latest

    steps:
      - name: Create Comment on issues with APIs
        run: |
          gh api -X GET /repos/${ORGANIZATION}/${REPOSITORY}/topics --jq='.names'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZTION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
