name: testing gh api

on:
  push:
  
permissions: write-all

jobs:
  comment-with-api:
    runs-on: ubuntu-latest

    steps:
      - name: Create Comment on issues with APIs
        run: |
          gh api -X GET https://api.github.com/repos/ExpOrgJN/sample-repo-002/issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZTION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
