name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        with:
          issue-number: ${{ github.event.issue.number }}
          run: echo '${{ issue-number }}'
          shell: bash
